const mechanicalBenefits = [
  { title: 'Ford-backed coverage', text: 'Plan obligations are backed by Ford Motor Company and covered repairs use Ford-authorized parts.' },
  { title: 'Dealer support', text: 'Receive covered service from Ford and Lincoln dealers in the United States, Canada and Mexico.' },
  { title: 'Roadside assistance', text: 'Eligible plans include 24-hour towing and roadside benefits, subject to the issued agreement.' },
  { title: 'Rental support', text: 'Eligible covered repairs can include rental or alternate-transportation reimbursement within plan limits.' },
  { title: 'Transferable coverage', text: 'Remaining eligible coverage can transfer to a later owner; the agreement may require a transfer fee.' },
  { title: 'Ford-trained service', text: 'Covered repairs are completed by factory-trained technicians through Ford-authorized service facilities.' },
];

const mechanicalEligibility = [
  'Ford, Lincoln and eligible competitive-make vehicles may qualify; vehicle, state, use, age and mileage determine the available plan.',
  'New-plan coverage is measured from the original New Vehicle Limited Warranty start date and zero miles.',
  'Used-plan start and end rules depend on whether factory warranty remains at purchase; Bob Maxey verifies the correct plan type.',
  'Commercial, snow-plow, incomplete and medium-duty vehicles require the appropriate use or vehicle-class rating.',
  'Final eligibility is confirmed from the VIN, current mileage, in-service date, registration state and vehicle history before purchase.',
];

const mechanicalOptions = [
  'Plan terms can extend as far as 10 years or 175,000 miles on eligible non-EV vehicles; the quote shows only combinations available for the verified vehicle.',
  'The published standard deductible is $100. Eligible choices can include $0, $50, $200 and a disappearing deductible; $0 is not offered on used mechanical plans.',
  'Optional benefits can include Key Services, lighting coverage, rental choices and pickup/delivery or mobile service on eligible plans and vehicles.',
  'Ford Protect advertises interest-free installment options for eligible purchases that are not included in vehicle financing.',
];

const mechanicalLimits = [
  'Routine maintenance and wear items are not mechanical-breakdown coverage unless a separate maintenance benefit or plan applies.',
  'Collision, glass, body, paint, cosmetic damage, road hazards, rust and other items normally handled by auto insurance are not covered by a mechanical plan.',
  'Pre-existing conditions, unauthorized modifications, non-factory performance parts, misuse, racing and failures caused by lack of required maintenance are excluded.',
  'A non-covered part that causes a covered part to fail can affect coverage. Ford must authorize the repair before work begins, except where emergency-repair rules apply.',
  'Manufacturer recalls, an active warranty and insurance remain primary when they cover the repair. The issued agreement controls every claim.',
];

const claimSteps = [
  'Contact a Ford or Lincoln dealer and provide the vehicle identification number and Ford Protect plan information.',
  'The dealer diagnoses the concern and requests authorization for an eligible covered repair before work begins.',
  'Ford reviews the failure, coverage, maintenance history and any required inspection or teardown information.',
  'For an authorized repair, you pay the applicable deductible per eligible repair visit; covered parts, labor and taxes are handled under the agreement.',
  'Keep repair orders and receipts. Emergency, roadside, rental and travel reimbursements have separate notice and documentation rules.',
];

const mechanicalSources = {
  premium: 'https://fordprotect.ford.com/extendedserviceplan/index/downloadbrochure/careplan/premiumcare/',
  extra: 'https://fordprotect.ford.com/extendedserviceplan/index/downloadbrochure/careplan/extracare/',
  base: 'https://fordprotect.ford.com/extendedserviceplan/index/downloadbrochure/careplan/basecare/',
  powertrain: 'https://fordprotect.ford.com/extendedserviceplan/index/downloadbrochure/careplan/powertraincare/',
};

const engineFull = ['All internally lubricated parts', 'Cylinder block and heads', 'Factory-installed turbocharger or supercharger', 'Timing chain, gears or belt', 'Oil pan and oil pump', 'Water pump', 'Radiator and radiator fan', 'Fuel injectors and eligible fuel-system parts', 'PCM module', 'Seals and gaskets'];
const transmissionFull = ['Internally lubricated parts', 'Transmission case', 'Torque converter', 'Transfer case and internal parts', 'Transmission linkage and module', 'Release hubs and bearings', 'Mounts', 'Seals and gaskets'];
const axleFull = ['Front and rear axle shafts', 'Drive and final-drive housings with internal parts', 'Driveshaft', 'Universal and constant-velocity joints', 'Four-wheel-drive locking rings', 'Bearings', 'Viscous or flexible coupler', 'Seals and gaskets'];
const steeringFull = ['Electronic power-assisted steering', 'Power steering pump or actuator', 'Steering column and shaft', 'Steering gear housing and internal parts', 'Control valve and metal lines', 'Underbody linkages and couplings', 'Idler arm', 'Seals and gaskets'];
const brakesFull = ['Anti-lock brake module and sensor', 'Power brake booster', 'Calipers and wheel cylinders', 'Master cylinder', 'Combination valve', 'Metal lines and fittings', 'Parking-brake linkage and cables', 'Self-adjusters, springs, retainers and clips'];
const suspensionFull = ['Upper and lower ball joints', 'Control arms, shafts and bushings', 'Linkages and bushings', 'Load-leveling suspension components', 'MacPherson struts', 'Roll Stability Control components', 'Spindles and supports', 'Stabilizer bar and tie rods'];
const climateFull = ['A/C compressor, clutch, bearings, head and seals', 'A/C condenser and accumulator', 'Evaporator and field coil', 'Automatic temperature control', 'Heater blower motor', 'Heater control assembly and heater core', 'Instrument-panel registers and air ducts', 'Pulley'];
const electricalFull = ['Alternator and starter motor', 'Ignition module and switch', 'Fuel pump', 'Speedometer and odometer', 'Power mirrors and running boards electrical components', 'Wiper motors and switches', 'Wiring harnesses, excluding spark-plug wires', 'Factory-installed lighting when the applicable lighting coverage is included'];
const highTechFull = ['Adaptive cruise control', 'Blind-spot and cross-traffic electrical components', 'Automatic park-assist systems', 'Forward and reverse sensing systems', 'Reverse camera system', 'Electronic instrument cluster and message center', 'Factory-installed keyless entry and anti-theft systems', 'Power seat, window and door-lock motors', 'Rain-sensing wipers', 'SYNC factory hardware, excluding software upgrades'];

const makeMechanical = ({ name, id, stat, tagline, bestFor, model, groups }) => ({
  id,
  name,
  family: 'Mechanical coverage',
  type: 'Ford Protect Extended Service Plan',
  tagline,
  bestFor,
  stat,
  statLabel: 'covered components',
  maxTerm: 'Up to 10 years / 175,000 miles on eligible vehicles',
  image: '/assets/ford-official/ford-why-plan.png',
  coverageModel: model,
  coverageGroups: groups,
  benefits: mechanicalBenefits,
  eligibility: mechanicalEligibility,
  options: mechanicalOptions,
  limits: mechanicalLimits,
  useSteps: claimSteps,
  sourceDocuments: [
    { label: `${name} brochure`, url: mechanicalSources[id] },
    { label: 'Sample Ford Protect terms and conditions', url: 'https://fordprotect.ford.com/fl8250contract' },
  ],
  quoteMode: 'mechanical',
});

const premiumGroups = [
  { title: 'Engine', summary: 'Major engine systems and factory-installed forced-induction components.', items: engineFull },
  { title: 'Transmission', summary: 'Automatic and manual transmission, torque-converter and transfer-case components.', items: transmissionFull },
  { title: 'Electrical', summary: 'A broad range of starting, charging, control, convenience and wiring components.', items: electricalFull },
  { title: 'High-tech', summary: 'Many factory-installed driver-assistance, camera, sensing and convenience technologies.', items: highTechFull },
  { title: 'Steering', summary: 'Manual, hydraulic and eligible electronic steering components.', items: steeringFull },
  { title: 'Brakes', summary: 'Hydraulic, parking-brake and anti-lock system components; friction wear items are excluded.', items: brakesFull },
  { title: 'Air conditioning & heating', summary: 'Climate-control, compressor, condenser, evaporator and heater components.', items: climateFull },
  { title: 'Front & rear suspension', summary: 'Control arms, joints, linkages, supports and eligible suspension-control components.', items: suspensionFull },
  { title: 'Front & rear drive axle', summary: 'Housings, shafts, joints, driveshafts and eligible four-wheel-drive components.', items: axleFull },
  { title: 'Safety & audio', summary: 'Selected factory-installed restraint, safety, radio, speaker and entertainment hardware.', items: ['Airbag and diagnostic modules', 'Safety-belt retractors, buckles, sensors and motors', 'Collision-avoidance system hardware', 'Factory-installed radio, speakers and amplifier', 'Rear entertainment system', 'Factory-installed cellular receiver and antenna hardware'] },
  { title: 'Emissions', summary: 'Selected electronic, sensor and vapor-management components.', items: ['Electronic throttle control', 'EGR control components', 'Mass-air-flow and intake-air-temperature sensor', 'Oxygen and knock sensors', 'EVAP vapor storage canister', 'Variable camshaft timing phasers', 'DEF and reductant system components, excluding catalyst'] },
];

export const productDetails = {
  premium: makeMechanical({ name: 'PremiumCARE', id: 'premium', stat: '1,000+', tagline: 'Ford Protect’s most comprehensive mechanical and high-tech coverage.', bestFor: 'Owners who want broad protection that is easier to understand by its exclusions than by a short list of covered parts.', model: 'PremiumCARE is exclusionary coverage: eligible mechanical and electrical failures are covered unless the agreement specifically excludes them. The groups below are searchable examples, not a limit on coverage.', groups: premiumGroups }),
  extra: makeMechanical({ name: 'ExtraCARE', id: 'extra', stat: '113', tagline: 'Enhanced protection for drivability, climate, electrical and selected high-tech systems.', bestFor: 'Owners who want core mechanical coverage plus more of the daily-use systems that affect comfort and drivability.', model: 'ExtraCARE is listed-component coverage. It includes PowertrainCARE and BaseCARE components plus the additional ExtraCARE items shown in Ford’s component schedule.', groups: [
    { title: 'Engine', summary: 'Powertrain and BaseCARE engine protection plus selected fuel-system parts.', items: [...engineFull.filter((item) => !item.includes('PCM')), 'Flywheel ring gear', 'Diesel lift pump', 'Gas and diesel fuel injectors'] },
    { title: 'Transmission', summary: 'Major transmission, torque-converter and transfer-case components.', items: transmissionFull },
    { title: 'Electrical', summary: 'Selected starting, charging, switching and wiring hardware.', items: ['Alternator', 'Electronic ignition module', 'Fuel pump', 'Ignition switch', 'Radiator fan relay', 'Speedometer/odometer', 'Starter motor and solenoid', 'Wiper motors', 'Eligible wiring harnesses'] },
    { title: 'High-tech', summary: 'Selected electronic comfort and convenience components.', items: ['Adaptive cruise control', 'Electronic instrument cluster', 'Keyless entry hardware', 'Power seat motors', 'Power window motors and regulators', 'Power antenna', 'Power door locks and clips', 'Electronic air-suspension components', 'Speed control'] },
    { title: 'Steering, brakes & suspension', summary: 'Listed steering, brake and front-suspension components.', items: [...steeringFull, ...brakesFull.slice(0, 6), ...suspensionFull.slice(0, 6)] },
    { title: 'Air conditioning & heating', summary: 'A broader climate-control list than BaseCARE.', items: climateFull },
    { title: 'Front & rear drive axle', summary: 'Listed front-, rear- and four-wheel-drive axle components.', items: axleFull },
  ] }),
  base: makeMechanical({ name: 'BaseCARE', id: 'base', stat: '84', tagline: 'Essential protection across major mechanical and selected vehicle systems.', bestFor: 'Owners who want more than powertrain-only protection while keeping coverage focused on major components.', model: 'BaseCARE is listed-component coverage. It includes PowertrainCARE items plus the additional BaseCARE steering, suspension, brake, climate and electrical items shown below.', groups: [
    { title: 'Engine', summary: 'Powertrain components plus selected fuel and balance hardware.', items: [...engineFull.filter((item) => !item.includes('Fuel injectors') && !item.includes('PCM') && !item.includes('Radiator')), 'Metal fuel lines', 'Harmonic balancer and bolt', 'Diesel injector pump'] },
    { title: 'Transmission', summary: 'Core transmission and transfer-case components.', items: transmissionFull.slice(0, 6) },
    { title: 'Electrical', summary: 'Selected starting, charging, switching and wiring hardware.', items: ['Alternator', 'Electronic ignition module', 'Fuel pump', 'Ignition switch', 'Radiator fan relay', 'Speedometer/odometer', 'Starter motor and solenoid', 'Wiper motors', 'Eligible wiring harnesses'] },
    { title: 'Steering', summary: 'Listed manual, hydraulic and electronic steering components.', items: steeringFull },
    { title: 'Brakes', summary: 'Listed hydraulic and parking-brake hardware; pads, linings, drums and rotors are wear items.', items: brakesFull.filter((item) => !item.includes('Anti-lock')) },
    { title: 'Front suspension', summary: 'Listed front-suspension joints, arms, linkages and supports.', items: suspensionFull.filter((item) => !item.includes('Load-leveling') && !item.includes('Roll Stability')) },
    { title: 'Air conditioning', summary: 'Selected A/C compressor, condenser and evaporator hardware.', items: climateFull.filter((item) => !item.includes('Automatic') && !item.includes('Heater') && !item.includes('registers')) },
    { title: 'Front & rear drive axle', summary: 'Core axle, driveshaft and joint components.', items: axleFull },
  ] }),
  powertrain: makeMechanical({ name: 'PowertrainCARE', id: 'powertrain', stat: '29', tagline: 'Core protection for critical engine, transmission and drive-axle components.', bestFor: 'Owners who want focused protection against eligible failures in the systems that make the vehicle move.', model: 'PowertrainCARE is listed-component coverage. Only the engine, transmission and front- and rear-wheel-drive components named in the agreement are covered.', groups: [
    { title: 'Engine', summary: 'Core internal and external engine hardware.', items: ['Cylinder block, cylinder heads and internally lubricated parts', 'Exhaust and intake manifolds and bolts', 'Factory-installed turbocharger or supercharger', 'Timing chain, gears or belt and cover', 'Flywheel and valve covers', 'Oil pan and oil pump', 'Water pump', 'Thermostat and housing', 'Seals and gaskets'] },
    { title: 'Transmission', summary: 'Core automatic/manual transmission and transfer-case hardware.', items: ['Transmission case and internally lubricated parts', 'Torque converter', 'Transfer case and internal parts', 'Transmission control module', 'Seals and gaskets'] },
    { title: 'Front-wheel drive', summary: 'Core final-drive, shaft and joint hardware.', items: ['Front drive housing and internal parts', 'Rear axle housing for AWD and internal parts', 'Universal and constant-velocity joints', 'Axle shafts', 'Automatic front locking hubs', 'Seals and gaskets'] },
    { title: 'Rear-wheel drive', summary: 'Core drive-axle and driveshaft hardware.', items: ['Drive axle housing and internal parts', 'Front axle housing for 4x4 and internal parts', 'Universal and constant-velocity joints', 'Axle shafts and driveshafts', 'Seals and gaskets'] },
  ] }),
};

const evBenefits = mechanicalBenefits;
const evEligibility = [
  'Eligible Ford, Lincoln and competitive-make electric vehicles may qualify; VIN, state, age, mileage, use and warranty record determine availability.',
  'New EV plan coverage begins at the original in-service date and zero miles. Used-plan rules depend on factory-warranty status at purchase.',
  'Published eligible terms can extend up to 10 years or 150,000 miles; only available combinations appear after vehicle verification.',
  'The high-voltage battery assembly has its own manufacturer warranty and is not eligible for Ford Protect extended-service-plan coverage.',
];
const evOptions = [
  'The published standard deductible is $100. Eligible new-plan choices can include $0, $50, $200 and disappearing deductible; used-plan choices differ.',
  'Key Services, rental and other options depend on the plan, vehicle and state.',
  'PremiumCARE Plus EV combines mechanical/electrical coverage with scheduled EV maintenance and selected wear items.',
];
const evLimits = [
  'The high-voltage battery assembly and its manufacturer-warranty items are not extended-service-plan coverage.',
  ...mechanicalLimits,
];
const evSources = {
  'premium-plus-ev': 'https://fordprotect.ford.com/media/brochure/ford/64172_1643b%20FP%20PremiumCARE%20Plus%20EV%20Bro%20OCT%202024.pdf',
  'premium-ev': 'https://fordprotect.ford.com/extended-service-plan',
  'extra-ev': 'https://fordprotect.ford.com/media/brochure/ford/64172_1631b%20FP%20ExtraCARE%20EV%20Bro%20OCT%202024%20Final%207_24_23.pdf',
  'base-ev': 'https://fordprotect.ford.com/media/brochure/ford/64172_1626b%20FP%20BaseCARE%20EV%20Bro%20OCT%202024%20Final%207_24_23.pdf',
};

const evPremiumGroups = [
  { title: 'Drive motors', summary: 'Electric drive and supporting cooling components.', items: ['Drive motors and mounts', 'Oil pump', 'PCM module', 'Radiator and radiator fan', 'Water pump', 'Seals and gaskets'] },
  { title: 'Electrical', summary: 'Charging, conversion, control and factory electrical hardware.', items: ['Battery charger', 'Battery Energy Control Module', 'Voltage converter assembly', 'Inverter system controller modules', 'On-board battery charging cord', 'Primary electric drive', 'Instrument cluster and gauges', 'Wiper motors and eligible wiring harnesses'] },
  { title: 'High-tech', summary: 'Many factory-installed sensing, driver-assistance and convenience systems.', items: highTechFull },
  { title: 'Steering', summary: 'Eligible electronic and mechanical steering components.', items: steeringFull },
  { title: 'Brakes', summary: 'Eligible brake-control and hydraulic components.', items: brakesFull },
  { title: 'Front & rear suspension', summary: 'Eligible joints, arms, bushings, links and stability components.', items: suspensionFull },
  { title: 'Air conditioning & heating', summary: 'Eligible compressor, climate-control, evaporator and heater components.', items: climateFull },
  { title: 'Safety & audio', summary: 'Selected factory-installed restraint, safety and entertainment hardware.', items: premiumGroups.find((group) => group.title === 'Safety & audio').items },
];

const makeEv = ({ id, name, stat, tagline, bestFor, model, groups }) => ({
  id, name, family: 'Electric vehicles', type: 'Ford Protect EV Extended Service Plan', tagline, bestFor, stat, statLabel: 'covered components', maxTerm: 'Up to 10 years / 150,000 miles on eligible vehicles', image: '/assets/ford-official/ford-why-2.png', coverageModel: model, coverageGroups: groups, benefits: evBenefits, eligibility: evEligibility, options: evOptions, limits: evLimits, useSteps: claimSteps, sourceDocuments: [{ label: `${name} Ford brochure or overview`, url: evSources[id] }], quoteMode: 'electric',
});

Object.assign(productDetails, {
  'premium-plus-ev': makeEv({ id: 'premium-plus-ev', name: 'PremiumCARE Plus EV', stat: '1,000+', tagline: 'Comprehensive EV component protection plus scheduled maintenance in one plan.', bestFor: 'EV owners who want one Ford-backed path for eligible repairs, scheduled service and selected wear items.', model: 'PremiumCARE Plus EV combines PremiumCARE EV with Premium Maintenance EV. Mechanical/electrical failures follow the component agreement; maintenance follows the vehicle schedule and selected service interval.', groups: [...evPremiumGroups, { title: 'Scheduled maintenance & wear', summary: 'Vehicle-schedule service plus selected wear items.', items: ['Multi-point inspections', 'Tire rotations', 'Cabin air filter at scheduled intervals', 'Brake pads and linings', 'Shock absorbers and struts', 'Wiper blades', 'Washer-fluid top-offs'] }] }),
  'premium-ev': makeEv({ id: 'premium-ev', name: 'PremiumCARE EV', stat: '1,000+', tagline: 'Broad protection for eligible EV drive, electrical and high-tech systems.', bestFor: 'EV owners who want Ford Protect’s broadest eligible component coverage without bundled maintenance.', model: 'PremiumCARE EV provides broad listed protection for eligible EV motors, electrical, high-tech, steering, brakes, suspension and climate systems. The high-voltage battery assembly remains outside the plan.', groups: evPremiumGroups }),
  'extra-ev': makeEv({ id: 'extra-ev', name: 'ExtraCARE EV', stat: '113', tagline: 'Enhanced protection for selected EV systems that affect performance and drivability.', bestFor: 'EV owners who want more daily-use electrical, climate and high-tech coverage than BaseCARE EV.', model: 'ExtraCARE EV is listed-component coverage. The agreement covers only the named parts in each system group.', groups: [
    { title: 'Drive motors', summary: 'Selected electric-drive and cooling hardware.', items: ['Drive motors and mounts', 'Oil pump', 'Radiator and radiator fan', 'Water pump', 'Seals and gaskets'] },
    { title: 'Electrical', summary: 'Selected vehicle electrical and control hardware.', items: ['Heated-backglass electrical components', 'Ignition switch', 'Radiator fan relay', 'Speedometer/odometer', 'Manually operated electrical switches', 'Wiper motors', 'Eligible wiring harnesses'] },
    { title: 'High-tech', summary: 'Selected factory-installed convenience and driver-support hardware.', items: ['Adaptive cruise control', 'Selected electronic air-suspension components', 'Electronic instrument cluster', 'Keyless entry hardware', 'Power antenna', 'Power door locks and clips', 'Power seat and window motors', 'SecuriCode hardware', 'Speed control'] },
    { title: 'Steering', summary: 'Selected electronic and mechanical steering components.', items: ['Column lock', 'Control valve and cooler', 'Idler arm', 'Electric power-steering actuator', 'Steering gear housing and internal parts', 'Underbody linkages and couplings', 'Seals and gaskets'] },
    { title: 'Brakes & front suspension', summary: 'Selected hydraulic, anti-lock and front-suspension hardware.', items: [...brakesFull, ...suspensionFull.filter((item) => !item.includes('Load-leveling') && !item.includes('Roll Stability'))] },
    { title: 'Air conditioning & heating', summary: 'Selected A/C and heating hardware.', items: climateFull },
    { title: 'Drive axle', summary: 'Selected EV axle hardware.', items: ['Axle shafts', 'Seals and gaskets'] },
  ] }),
  'base-ev': makeEv({ id: 'base-ev', name: 'BaseCARE EV', stat: '84', tagline: 'Essential protection for selected EV drivability and performance components.', bestFor: 'EV owners seeking focused protection for drive motors and selected major systems.', model: 'BaseCARE EV is listed-component coverage. Only the named components in its Ford schedule are covered.', groups: [
    { title: 'Drive motors', summary: 'Core electric-drive hardware.', items: ['Drive motors', 'Oil pump', 'Water pump', 'Seals and gaskets'] },
    { title: 'Electrical', summary: 'Selected electrical and control hardware.', items: ['Heated-backglass electrical components', 'Ignition switch', 'Radiator fan relay', 'Speedometer/odometer', 'Manually operated electrical switches', 'Wiper motors', 'Eligible wiring harnesses'] },
    { title: 'Steering', summary: 'Selected electronic and mechanical steering components.', items: ['Column lock', 'Control valve and cooler', 'Idler arm', 'Electric power-steering actuator', 'Steering gear housing and internal parts', 'Underbody linkages and couplings', 'Seals and gaskets'] },
    { title: 'Brakes', summary: 'Selected hydraulic and parking-brake components.', items: brakesFull.filter((item) => !item.includes('Anti-lock')) },
    { title: 'Front suspension', summary: 'Selected front-suspension hardware.', items: suspensionFull.filter((item) => !item.includes('Load-leveling') && !item.includes('Roll Stability')) },
    { title: 'Air conditioning', summary: 'Selected A/C hardware.', items: climateFull.filter((item) => !item.includes('Automatic') && !item.includes('Heater') && !item.includes('registers')) },
    { title: 'Drive axle', summary: 'Selected EV axle hardware.', items: ['Axle shafts'] },
  ] }),
});

const dealerClaimSteps = [
  'Contact the selling dealer or the administrator shown on the agreement before arranging service.',
  'Describe the damage or covered event and provide the VIN, plan information, photos or receipts requested by the administrator.',
  'Use the authorized dealer, repair facility or mobile provider identified for the product.',
  'Obtain authorization before repair or replacement. Pay only expenses the agreement assigns to you.',
  'Keep the completed repair order and all claim documentation for your records.',
];

const makeDealerProduct = ({ id, name, family = 'Vehicle care', tagline, bestFor, stat, statLabel, maxTerm, image, model, groups, benefits, eligibility, options, limits, source }) => ({
  id, name, family, type: 'Ford Protect dealer product', tagline, bestFor, stat, statLabel, maxTerm, image, coverageModel: model, coverageGroups: groups, benefits, eligibility, options, limits, useSteps: dealerClaimSteps, sourceDocuments: source ? [{ label: `${name} official Ford information`, url: source }] : [], quoteMode: 'dealer',
});

Object.assign(productDetails, {
  'premium-maintenance': makeDealerProduct({ id: 'premium-maintenance', name: 'Premium Maintenance Plan', family: 'Maintenance', tagline: 'Scheduled maintenance and selected wear items at a $0 deductible.', bestFor: 'Gas, diesel and hybrid owners who want to pre-plan factory-schedule service and eligible wear replacement.', stat: '$0', statLabel: 'deductible for covered maintenance', maxTerm: 'Service interval and term choices vary by vehicle', image: '/assets/ford-official/ford-maintenance-wide.png', model: 'Services follow the vehicle’s Scheduled Maintenance Guide and the interval purchased. This is maintenance coverage, not a substitute for mechanical-breakdown protection.', groups: [
    { title: 'Scheduled service', summary: 'Routine service based on the vehicle and purchased interval.', items: ['Engine oil and filter changes', 'Multi-point inspections', 'Tire rotations', 'Diesel exhaust fluid fill when scheduled maintenance is performed'] },
    { title: 'Selected wear items', summary: 'Wear replacement when covered by the purchased plan.', items: ['Brake pads and linings', 'Shock absorbers and struts', 'Spark plugs', 'Clutch discs', 'Engine belts', 'Coolant hoses, clamps and O-ring seals', 'Wiper blades'] },
    { title: 'Multi-point inspection', summary: 'A structured inspection at covered service visits.', items: ['Lights, signals, horn and wipers', 'Windshield condition', 'Engine air filter', 'Fluid and exhaust leaks', 'Steering and suspension', 'Belts, clutch and tires', 'Applicable fluid-level checks and fill'] },
  ], benefits: [{ title: 'Lock in service', text: 'Bundle eligible future maintenance visits in advance.' }, { title: 'Genuine service', text: 'Service through participating Ford dealerships with Ford-authorized parts.' }, { title: 'Transfer option', text: 'Eligible remaining coverage may transfer; a fee can apply.' }, { title: 'First-Day Rental option', text: 'An eligible rental option can be selected with the plan.' }], eligibility: ['Available for eligible gas, diesel and hybrid vehicles.', 'Plan services are based on the vehicle’s maintenance guide and purchased service frequency.', 'Ford’s published material identifies 5,000-, 7,500- and 10,000-mile service intervals on eligible vehicles.', 'Vehicle, state and time-of-purchase rules determine the available plan.'], options: ['Choose the eligible time, mileage, service frequency and oil type shown for the verified vehicle.', 'A full-synthetic-oil option is available on many eligible vehicles.', 'Severe-duty maintenance items can be available with 5,000-mile intervals.', 'First-Day Rental may be added where offered.'], limits: ['Only services and wear items included in the purchased schedule are covered.', 'Repairs for failures are not maintenance-plan services unless another warranty or service plan applies.', 'Damage, abuse, missed maintenance and non-scheduled work are not covered maintenance.', 'The issued agreement and vehicle maintenance guide control service timing and limits.'], source: 'https://fordprotect.ford.com/premium-maintenance-plan' }),
  'premium-maintenance-ev': makeDealerProduct({ id: 'premium-maintenance-ev', name: 'Premium Maintenance EV', family: 'Maintenance', tagline: 'Scheduled EV inspections, service and selected wear-item coverage.', bestFor: 'EV owners who want eligible scheduled visits and common wear items bundled in advance.', stat: 'EV', statLabel: 'scheduled maintenance coverage', maxTerm: 'Up to 10 years / 150,000 miles where eligible', image: '/assets/ford-official/ford-why-2.png', model: 'Coverage follows the EV’s maintenance schedule and the service interval selected. High-voltage-battery failures are not maintenance items.', groups: [
    { title: 'Scheduled visits', summary: 'Routine EV service at the selected maintenance frequency.', items: ['Multi-point inspections', 'Tire rotations', 'Cabin air filter replacement at scheduled intervals', 'Washer-fluid top-offs'] },
    { title: 'Selected wear items', summary: 'Eligible wear replacement included by the plan.', items: ['Brake pads and linings', 'Shock absorbers and struts', 'Wiper blades'] },
  ], benefits: [{ title: 'EV-focused schedule', text: 'Coverage is organized around the maintenance needs of an electric vehicle.' }, { title: '$0 maintenance deductible', text: 'Covered maintenance services are performed without a plan deductible.' }, { title: 'Transfer option', text: 'Eligible remaining coverage may transfer; a fee can apply.' }, { title: 'Ford service network', text: 'Use participating Ford dealerships for eligible services.' }], eligibility: evEligibility, options: ['Choose an eligible time/mileage combination and maintenance frequency.', 'Premium Maintenance EV can be purchased separately or included with PremiumCARE Plus EV.'], limits: ['High-voltage-battery repair is not a maintenance service.', 'Only scheduled services and selected wear items listed by the plan are included.', 'The issued agreement and vehicle schedule control visit timing and quantities.'], source: evSources['premium-plus-ev'] }),
  'continued-service': makeDealerProduct({ id: 'continued-service', name: 'Continued Service Plan', family: 'Maintenance', tagline: 'A Ford-backed path for eligible owners whose existing Ford Protect coverage is ending.', bestFor: 'Owners who want to continue mechanical-breakdown protection after an eligible Ford Protect plan.', stat: 'CSP', statLabel: 'continued coverage path', maxTerm: 'Published total vehicle age/mileage limits can reach 14 years / 160,000 miles', image: '/assets/ford-official/ford-maintenance-wide.png', model: 'CSP is designed to follow an expiring Ford Protect plan without duplicating active coverage. Ultimate is exclusionary; Standard Plus covers the listed component groups.', groups: [
    { title: 'CSP Ultimate', summary: 'The broadest CSP option, covering moving lubricated parts and electrical components except agreement exclusions.', items: ['Engine', 'Transmission', 'Electrical', 'Brakes', 'Front and rear suspension', 'Front and rear drive axle', 'Air conditioning and heating', 'Steering', 'High-tech', 'Emissions', 'Audio'] },
    { title: 'CSP Standard Plus', summary: 'Listed coverage for major mechanical, electrical and selected high-tech groups.', items: ['Engine', 'Transmission', 'Electrical', 'Brakes', 'Front and rear suspension', 'Front and rear drive axle', 'Air conditioning and heating', 'Steering', 'High-tech'] },
  ], benefits: [{ title: 'Ford-backed continuation', text: 'Continue eligible protection through a Ford Protect product.' }, { title: 'Rental benefits', text: 'Eligible covered repairs include agreement-defined rental support.' }, { title: 'Ford service network', text: 'Use Ford/Lincoln dealer support for covered repairs.' }, { title: 'Low out-of-pocket exposure', text: 'Pay the applicable deductible for authorized covered visits.' }], eligibility: ['Created for eligible vehicles after expiration of Ford Protect coverage.', 'Vehicle age, mileage, state, prior plan and lapse status determine eligibility.', 'A specialist must verify the plan record and available start date.'], options: ['Choose CSP Ultimate or CSP Standard Plus when offered.', 'Available term, mileage and deductible choices are returned after plan-record verification.'], limits: ['CSP is not duplicate coverage and does not extend an active agreement by itself.', 'Ultimate and Standard Plus use different coverage models.', ...mechanicalLimits.slice(0, 3)], source: 'https://fordprotect.ford.com/continued-service-plan' }),
  tirecare: makeDealerProduct({ id: 'tirecare', name: 'TireCARE Plus', tagline: 'Tire-and-wheel protection for covered road-hazard damage.', bestFor: 'Owners who want help with potholes, nails, glass, metal, debris and other covered road hazards.', stat: '7 yrs', statLabel: 'up to, with no mileage limit', maxTerm: 'Available on eligible new and used vehicles at time of sale', image: '/assets/ford-official/tirecare.png', model: 'Covers eligible repair or replacement costs when a road hazard damages a covered tire or wheel. The agreement defines the tire condition, replacement standard and facility rules.', groups: [
    { title: 'Road hazards', summary: 'Covered events identified by Ford.', items: ['Glass or metal in the road', 'Potholes and pavement damage', 'Debris and nails', 'Eligible blowouts caused by a road hazard'] },
    { title: 'Tire benefits', summary: 'Eligible repair or like-kind replacement.', items: ['Flat-tire repair', 'Replacement when non-repairable and tread requirements are met', 'Mounting and balancing', 'Valve stem and disposal', 'Applicable labor and sales tax'] },
    { title: 'Wheel benefits', summary: 'Eligible structural and cosmetic wheel coverage.', items: ['Road-hazard wheel repair or replacement', 'Cosmetic coverage for alloy, aluminum and steel wheels'] },
  ], benefits: [{ title: 'No occurrence limit', text: 'Ford’s current page states no limit on claim occurrences or claim benefits during the contract.' }, { title: 'Replacement coverage continues', text: 'Eligible replacement tires and wheels remain covered for the contract duration.' }, { title: 'Run-flat eligible', text: 'Run-flat tire technology is included where vehicle and agreement are eligible.' }, { title: 'Towing reimbursement', text: 'Up to $100 to the nearest Ford/Lincoln dealer or tire facility under published terms.' }], eligibility: ['Available on eligible new and used vehicles at the time of vehicle sale only.', 'No mileage limitation; term options can extend up to seven years.', 'The damaged tire must meet agreement tread-depth and condition requirements.'], options: ['An off-road coverage option can be available on eligible vehicles.', 'Select the term offered for the vehicle at purchase.'], limits: ['Ordinary tread wear, pre-existing damage, cosmetic damage outside the purchased benefit and non-road-hazard causes are not automatically covered.', 'Published replacement guidance requires more than 3/32 inch of tread remaining for a non-repairable tire.', 'Authorization and facility requirements apply.'], source: 'https://fordprotect.ford.com/tirecare' }),
  dentcare: makeDealerProduct({ id: 'dentcare', name: 'DentCARE', tagline: 'Paintless dent repair for eligible minor dents, dings and creases.', bestFor: 'Owners who want to preserve factory finish without conventional bodywork for eligible small dents.', stat: '8 yrs', statLabel: 'up to, with no claim-benefit limit', maxTerm: 'Eligible new and used vehicles', image: '/assets/ford-official/dentcare.png', model: 'Uses paintless dent repair to flex accessible metal panels back to shape without sanding, paint or body filler.', groups: [{ title: 'Paintless dent repair', summary: 'Eligible minor damage on accessible metal body panels.', items: ['Door dings', 'Minor dents', 'Minor creases', 'Dents no larger than four inches in an accessible repair area'] }], benefits: [{ title: '$0 deductible', text: 'Published covered DentCARE repairs have no deductible.' }, { title: 'Flexible location', text: 'Covered repairs can be arranged at the selling dealer, home or business.' }, { title: 'Factory finish preserved', text: 'PDR avoids sanding, repainting and body filler on eligible damage.' }, { title: 'Transferable', text: 'Eligible remaining coverage can transfer to a later owner.' }], eligibility: ['Available for eligible new and used vehicles.', 'Damage must be within an accessible repair area on a covered metal body panel.', 'Term options can extend up to eight years.'], options: ['Choose an eligible term at vehicle purchase.', 'Mobile or dealer-location service depends on provider availability.'], limits: ['Dents or dings larger than four inches are not covered by the published benefit.', '100% plastic, fiberglass or other non-metal composite body panels are excluded.', 'Paint damage, collision/body repair and inaccessible damage can require conventional repair and are not PDR benefits.'], source: 'https://fordprotect.ford.com/dentcare' }),
  windshieldcare: makeDealerProduct({ id: 'windshieldcare', name: 'WindshieldCARE', tagline: 'Convenient repair for eligible chips and minor cracks in the front windshield.', bestFor: 'Owners who want no-deductible repair before a small road-debris chip spreads.', stat: '$0', statLabel: 'deductible on covered repair', maxTerm: 'Up to eight years; at time of vehicle sale only', image: '/assets/ford-official/windshieldcare.png', model: 'Covers repair—not replacement—of eligible minor chips and cracks in the front windshield.', groups: [{ title: 'Front-windshield repair', summary: 'Eligible minor damage caused by propelled rocks, metal or road debris.', items: ['Minor chip repair', 'Minor crack repair up to the agreement limit', 'Service at the selling dealer, home or work when available'] }], benefits: [{ title: 'No occurrence limit', text: 'Ford’s current page states no limit on claim occurrences.' }, { title: '$0 deductible', text: 'Published covered windshield repairs have no deductible.' }, { title: 'Convenient service', text: 'Repair can be arranged at the selling dealer, home or work where available.' }, { title: 'Value preservation', text: 'Timely repair can help preserve the windshield and vehicle value.' }], eligibility: ['Available on eligible new and used vehicles at the time of sale only.', 'Terms can extend up to eight years.', 'Not eligible for sale in Florida under Ford’s current page.'], options: ['Choose the available term at vehicle purchase.', 'EV owners may have a separate WindshieldCARE Plus EV path.'], limits: ['Stress cracks and cracks more than six inches are not covered by the published benefit.', 'Replacement is not included in standard WindshieldCARE.', 'Damage outside the front windshield is not covered.'], source: 'https://fordprotect.ford.com/windshieldcare' }),
  'windshieldcare-ev': makeDealerProduct({ id: 'windshieldcare-ev', name: 'WindshieldCARE Plus EV', tagline: 'EV front-windshield repair plus one OEM-glass replacement and calibration.', bestFor: 'Eligible EV owners whose windshield systems can require OEM glass and calibration after replacement.', stat: '1', statLabel: 'replacement plus eligible repairs', maxTerm: 'Up to eight years; at time of vehicle sale only', image: '/assets/ford-official/windshieldcare.png', model: 'Covers eligible front-windshield chip/crack repair plus one front-windshield replacement and calibration using OEM glass.', groups: [{ title: 'Front-windshield benefits', summary: 'Repair and one replacement under the plan.', items: ['Eligible minor chip and crack repair', 'One front-windshield replacement', 'Required calibration tied to the covered replacement', 'OEM replacement glass'] }], benefits: [{ title: '$0 deductible', text: 'Published covered service has no deductible.' }, { title: 'OEM glass', text: 'The one covered replacement uses OEM glass under Ford’s published benefit.' }, { title: 'Calibration included', text: 'Calibration associated with the covered replacement is included.' }, { title: 'Mobile convenience', text: 'Service may be completed at home, office or the selling dealer.' }], eligibility: ['Available on eligible new and used EVs at the time of sale only.', 'Terms can extend up to eight years.', 'Ford’s current page says it is not available in Florida, Texas, Georgia, New York or Maine.'], options: ['Choose the available term at vehicle purchase.'], limits: ['Damage outside the front windshield is excluded.', 'Stress cracks and cracks more than six inches are excluded.', 'Hail, vandalism and neglect are excluded under Ford’s published description.', 'Only one windshield replacement is included.'], source: 'https://fordprotect.ford.com/windshieldcare-plus-ev' }),
  triplecare: makeDealerProduct({ id: 'triplecare', name: 'TripleCARE Plus', tagline: 'Tire-and-wheel, paintless-dent and windshield-repair benefits in one product.', bestFor: 'Owners who prefer one agreement for three common vehicle-care concerns.', stat: '3-in-1', statLabel: 'tire, dent and glass protection', maxTerm: 'Unlimited mileage and up to eight years', image: '/assets/ford-official/triplecare.png', model: 'Combines TireCARE Plus, DentCARE and WindshieldCARE benefits. Each benefit keeps its own damage, size, tread and service rules.', groups: [
    { title: 'Tire & wheel', summary: 'Eligible road-hazard repair or replacement.', items: ['Road-hazard tire repair/replacement', 'Road-hazard wheel repair/replacement', 'Cosmetic coverage for alloy, aluminum and steel wheels', 'Up to $100 towing reimbursement'] },
    { title: 'Paintless dent repair', summary: 'Eligible small dents and dings without conventional bodywork.', items: ['Door dings', 'Minor dents and creases', 'Paintless repair that preserves factory finish'] },
    { title: 'Front windshield', summary: 'Eligible minor chip and crack repair.', items: ['Road-debris chip repair', 'Minor crack repair within published size limits'] },
  ], benefits: [{ title: '$0 deductible', text: 'Ford’s current TripleCARE Plus page states no deductible.' }, { title: 'No claim-count limit', text: 'Published coverage has no limit on the number of claims.' }, { title: 'Convenient repairs', text: 'Eligible dent and glass work may be completed at dealer, home or work.' }, { title: 'Off-road option', text: 'An eligible off-road TireCARE option can be added where offered.' }], eligibility: ['Available on eligible new and used vehicles at time of sale only.', 'Unlimited mileage and terms up to eight years under published material.', 'Tire, dent and glass eligibility rules each apply.'], options: ['Choose the available term at vehicle purchase.', 'Add the off-road option when the vehicle and agreement qualify.'], limits: ['Tire replacement requires the contract tread standard; Ford publishes more than 3/32 inch remaining.', 'Dents and dings larger than four inches are not covered.', 'Stress cracks and windshield cracks more than six inches are not covered.', 'Each component benefit has separate exclusions and service-location rules.'], source: 'https://fordprotect.ford.com/triplecare' }),
  surfacecare: makeDealerProduct({ id: 'surfacecare', name: 'SurfaceCARE', tagline: 'Graphene-infused ceramic protection for eligible interior and exterior surfaces.', bestFor: 'Owners who want agreement-defined protection from common environmental and everyday surface damage.', stat: '2–7 yrs', statLabel: 'available terms with unlimited mileage', maxTerm: 'Unlimited mileage on published term choices', image: '/assets/ford-official/surfacecare.png', model: 'A limited warranty for treated interior and exterior surfaces. Covered conditions are specific; it is not general collision, body or comprehensive insurance.', groups: [
    { title: 'Exterior surfaces', summary: 'Specified environmental and staining conditions.', items: ['Weather-induced fading and loss of gloss', 'Hard-water etching and industrial fallout', 'Bird droppings, acid rain and tree sap', 'Oxidation, insects, road salt and de-icing agents', 'Brake-dust or water spotting on eligible alloy/chrome wheels', 'Accidental paint overspray, ocean spray and fuel stains'] },
    { title: 'Interior surfaces', summary: 'Specified stains, fading and small burn damage.', items: ['Food, drink and oil-based stains', 'UV-induced fading', 'Blood, vomit, chewing gum and pet stains', 'Ink, dye, makeup and crayon', 'Burns on fabric or leather up to one inch', 'Air-freshener, hairspray and hand-sanitizer stains', 'Debris in perforated leather'] },
  ], benefits: [{ title: 'Interior and exterior', text: 'One product treats and protects eligible surfaces inside and outside.' }, { title: 'PFAS-free sealants', text: 'Ford’s current page describes the sealants as free of PFAS.' }, { title: 'Rental reimbursement', text: 'Agreement-defined rental-vehicle reimbursement is included.' }, { title: 'Unlimited mileage', text: 'Published 2–7 year term choices have unlimited mileage.' }], eligibility: ['Available terms and provider vary by state and selling dealer.', 'Protectant must be applied and maintained according to product instructions.', 'Covered surfaces and conditions are those named in the issued limited warranty.'], options: ['Choose an available term from two to seven years.', 'Transfer provisions and fees depend on the issued warranty.'], limits: ['Collision, wear, neglect, improper cleaning, pre-existing damage and untreated surfaces are not automatically covered.', 'Only the listed conditions and remedies in the issued limited warranty apply.', 'SurfaceCARE is not auto insurance or a general appearance guarantee.'], source: 'https://fordprotect.ford.com/surfacecare' }),
  theftcare: makeDealerProduct({ id: 'theftcare', name: 'TheftCARE', tagline: 'Visible theft deterrence, traceable identification and a limited theft benefit.', bestFor: 'Owners seeking an additional deterrent and limited reimbursement if a covered theft becomes a total loss.', stat: '$5,000', statLabel: 'published maximum limited benefit', maxTerm: 'Coverage options up to five years', image: '/assets/ford-official/theftcare.png', model: 'The vehicle receives traceable identification codes and visible warning labels. If a covered theft meets the agreement conditions, a limited benefit may help with replacement-vehicle or other eligible expenses.', groups: [
    { title: 'Theft deterrence', summary: 'Visible and traceable identification measures.', items: ['Distinctive anti-theft warning window labels', 'Traceable identification codes linked to the vehicle owner'] },
    { title: 'Limited warranty benefit', summary: 'Agreement-defined reimbursement after a covered total-loss theft.', items: ['Up to the selected published maximum benefit', 'Can be applied toward a replacement vehicle and other eligible expenses', 'Benefit level and availability vary by state'] },
  ], benefits: [{ title: 'Visible deterrent', text: 'Warning labels tell potential thieves the vehicle is protected.' }, { title: 'Recovery identification', text: 'Traceable codes can help identify the owner of a recovered vehicle.' }, { title: 'Replacement support', text: 'A covered benefit may help with deductible, payoff gap or replacement costs.' }, { title: 'Transfer option', text: 'The limited warranty may transfer; a fee can apply.' }], eligibility: ['Coverage options can extend up to five years.', 'Benefit amount, state availability and obligor vary by agreement.', 'Ford states TheftCARE is optional and is not insurance.', 'EtchCARE is the New York-specific product path.'], options: ['Select the eligible term and benefit level offered in the state.', 'TheftCARE may be included in vehicle financing when available.'], limits: ['The agreement can exclude theft outside covered territories, an unlocked vehicle or keys left inside, and theft by someone with access to the keys.', 'A benefit applies only when the agreement’s theft and total-loss conditions are met.', 'TheftCARE does not replace comprehensive auto insurance.'], source: 'https://fordprotect.ford.com/theftcare' }),
});

const specialtyUse = [
  'Submit the VIN, current mileage, in-service date, registration state and actual vehicle use to Bob Maxey.',
  'For commercial or upfit vehicles, provide body/upfit, GVWR, engine-hour and equipment details when requested.',
  'Bob Maxey checks Ford vehicle records, prior coverage and the correct specialty rating path.',
  'Review the returned plan, term, deductible, surcharge and agreement before purchase.',
  'After enrollment, use the agreement’s Ford/Lincoln service and authorization process for covered repairs.',
];

const specialty = ({ id, name, tagline, bestFor, model, groups, eligibility, options, limits }) => ({
  id, name, family: 'Certified & commercial', type: 'Dealer-assisted Ford Protect pathway', tagline, bestFor, stat: 'VIN', statLabel: 'record-level eligibility review', maxTerm: 'Available terms are returned after Ford verification', image: '/assets/ford-official/ford-why-3.png', coverageModel: model, coverageGroups: groups, benefits: mechanicalBenefits, eligibility, options, limits, useSteps: specialtyUse, sourceDocuments: [{ label: 'Ford Protect sample terms and definitions', url: 'https://fordprotect.ford.com/fl8250contract' }], quoteMode: 'dealer',
});

Object.assign(productDetails, {
  'fba-upgrade': specialty({ id: 'fba-upgrade', name: 'Ford Blue Advantage Upgrade', tagline: 'Additional component, term or mileage protection for eligible certified vehicles.', bestFor: 'Eligible Ford Gold or Blue Certified and competitive-make Blue Certified owners who want protection beyond included certification coverage.', model: 'Ford’s contract defines FBA Upgrade Coverage as additional-price mechanical coverage that can add component protection and longer term and/or mileage benefits.', groups: [{ title: 'Upgrade paths', summary: 'The available upgrade depends on certification level and vehicle record.', items: ['Gold Certified Ford vehicles', 'Blue Certified Ford vehicles', 'Blue Certified eligible competitive makes', 'Additional component coverage', 'Longer time and/or mileage benefits'] }], eligibility: ['The vehicle must have a qualifying Ford Blue Advantage certification record.', 'Certification level, make, age, mileage, prior coverage and state determine the available upgrade.', 'The VIN must be matched to Ford certification records before quoting.'], options: ['Choose from the upgrade levels, terms, mileage limits and deductibles returned for the certified vehicle.', 'Optional benefits depend on the returned agreement.'], limits: ['An upgrade does not change the underlying certification record.', 'Coverage begins, ends and overlaps with certified benefits as stated in the issued agreement.', ...mechanicalLimits.slice(1, 4)] }),
  'lincoln-cpo': specialty({ id: 'lincoln-cpo', name: 'Lincoln CPO Upgrade', tagline: 'Longer PremiumCARE time and/or mileage for eligible Lincoln certified vehicles.', bestFor: 'Lincoln Certified Pre-Owned owners who want to extend eligible PremiumCARE protection.', model: 'Ford’s contract defines L-CPO Upgrade Coverage as PremiumCARE purchased for an additional price to provide longer term and/or mileage coverage on Lincoln vehicles.', groups: [{ title: 'PremiumCARE upgrade', summary: 'Broad eligible coverage beyond the included certified term.', items: ['Eligible Lincoln CPO vehicle', 'PremiumCARE coverage model', 'Longer term and/or mileage', 'Ford record and dealer verification'] }, ...premiumGroups], eligibility: ['The Lincoln vehicle must have an eligible certified-pre-owned record.', 'VIN, certification date, age, mileage, state and current coverage determine the available upgrade.'], options: ['Select from eligible term, mileage and deductible choices returned for the VIN.', 'Available optional benefits depend on the issued agreement.'], limits: ['Upgrade coverage does not duplicate an active benefit and follows the issued start/end rules.', ...mechanicalLimits] }),
  commercial: specialty({ id: 'commercial', name: 'Commercial Vehicle Coverage', tagline: 'Correctly rated Ford Protect coverage for eligible business-use vehicles.', bestFor: 'Business, fleet, farm, delivery, construction and government-use vehicles requiring commercial classification.', model: 'Commercial use is a rating classification and may require a surcharge. Ford defines it by the vehicle’s primary business/government use or how the dealer reports the unit.', groups: [{ title: 'Eligibility review', summary: 'Bob Maxey matches vehicle class and use to the correct Ford path.', items: ['Business or government use', 'Farm, delivery or construction use', 'Fleet or multiple-driver use', 'Vehicle class and GVWR', 'Mileage and engine hours', 'Installed equipment and modifications'] }, { title: 'Available coverage', summary: 'Returned plans can include eligible mechanical groups under the selected Ford Protect agreement.', items: ['Engine and transmission', 'Drive axle', 'Steering and brakes', 'Electrical and climate', 'Selected high-tech components', 'Roadside and rental benefits when included'] }], eligibility: ['Actual use must be disclosed and rated correctly.', 'Vehicle class, GVWR, age, mileage, hours, equipment and state determine availability.', 'Taxi, emergency, livery, rental, snow-plow and other uses can have separate rules or exclusions.'], options: ['Plan level, term, mileage/hour limit, deductible and surcharge are returned after review.', 'Fleet or payment arrangements depend on Bob Maxey and Ford program availability.'], limits: ['Unreported commercial use can affect claims.', 'Upfit components are not automatically covered by a chassis service plan.', 'Severe or excluded uses and unauthorized modifications remain subject to agreement exclusions.'] }),
  incomplete: specialty({ id: 'incomplete', name: 'Incomplete Vehicle Coverage', tagline: 'A dedicated eligibility path for chassis cabs and vehicles completed by an upfitter.', bestFor: 'Incomplete Ford vehicles whose final body, equipment or use must be reviewed before rating.', model: 'Ford’s published brochure identifies separate time, mileage and engine-hour eligibility for incomplete vehicles. Coverage applies to eligible Ford chassis components under the issued plan—not automatically to the upfit.', groups: [{ title: 'Vehicle record review', summary: 'The original chassis and final-stage completion must be identified.', items: ['Original Ford chassis/VIN', 'Final-stage manufacturer', 'Body and upfit description', 'GVWR and commercial use', 'Mileage and engine hours'] }, { title: 'Eligible Ford systems', summary: 'The selected plan can cover eligible original Ford chassis components.', items: ['Engine and transmission', 'Drive axle', 'Steering and brakes', 'Electrical and climate', 'Other listed Ford components by plan level'] }], eligibility: ['Ford’s published material identifies review within 5 years, 100,000 miles or 4,000 hours of original in-service for incomplete vehicles; current Ford rules must be confirmed.', 'Final-stage documents, actual use and installed equipment may be required.', 'Coverage starts from original Ford in-service date and zero miles/hours on the published new-plan path.'], options: ['Choose from returned time/mileage/hour and deductible combinations.', 'Commercial-use rating and surcharges can apply.'], limits: ['Upfit, body and non-Ford components are not automatically covered.', 'Alterations that cause a failure can be excluded.', 'Coverage expires at the earliest selected time, mileage or engine-hour limit.'] }),
  'medium-duty': specialty({ id: 'medium-duty', name: 'Medium-Duty Coverage', tagline: 'Ford Protect options for eligible F-650/F-750 and other qualifying medium-duty units.', bestFor: 'Medium-duty operators who need vehicle-class, usage, mileage and hour-based coverage review.', model: 'Medium-duty vehicles use dedicated eligibility, towing and plan rules. The exact covered components depend on the returned Ford agreement and selected level.', groups: [{ title: 'Vehicle review', summary: 'Bob Maxey verifies the medium-duty configuration and operation.', items: ['Model and VIN', 'GVWR and body type', 'Engine and transmission', 'Commercial duty cycle', 'Mileage and engine hours', 'Upfit and installed equipment'] }, { title: 'Potential Ford-system coverage', summary: 'Available groups depend on the medium-duty plan returned.', items: ['Engine', 'Transmission', 'Drive axle', 'Steering and brakes', 'Electrical', 'Climate-control components'] }], eligibility: ['F-650/F-750 eligibility is reviewed within New Vehicle Limited Warranty under Ford’s published brochure.', 'VIN, GVWR, use, mileage, hours, body and equipment determine the available plan.', 'Dealer record review is required before any term is presented.'], options: ['Choose the plan, time/mileage/hour limit and deductible returned after review.', 'Published Ford terms identify up to $200 towing reimbursement per incident for medium-duty vehicles under applicable agreements.'], limits: ['Coverage ends at the earliest selected time, mileage or hour limit.', 'Non-Ford upfit components are not automatically covered.', 'Excluded uses, overload, unauthorized modifications and maintenance-related failures remain subject to contract terms.'] }),
});

export const allProductDetails = Object.values(productDetails);
